name: Deploy to S3 Bucket
on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  S3_BUCKET: deelaa.com
  DISTRIBUTION_ID: E33TXNI1I7XHWK


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Deploy to S3
        run: aws s3 sync ./ s3://$S3_BUCKET --delete

      - name: Invalidate CloudFront cache
        if: env.DISTRIBUTION_ID != ''
        run: 
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

